### ISSUE TITLE
Pasting in license Notes field doesn't work

### ISSUE THREAD

**Issue by olivierbon** [craftcms/.github#19]
### Description

If you try to add a note to a license, pasting text in the field will leave the **Save** button inactive. 

Typing in the same field works.

### Steps to reproduce

1. Add a note to a license by pasting text in (no typing).

https://user-images.githubusercontent.com/146041/200851304-9d80643e-de94-43f9-8426-c40ffea02c4e.mp4

**Comment by benjamindavid** [comment]
Fixed by https://github.com/craftcms/craftnet/commit/ab27bd228d83fcf46b90f74487e8697316270a34
Thanks!
