### ISSUE TITLE
[FR] Add a "known compatible with" field

### ISSUE THREAD

**Issue by khalwat** [craftcms/.github#36]
Taking a page out of the WordPress ecosystem, it'd be useful for people using plugins to cast an affirmational vote that a plugin does work on various major versions of Craft CMS.

The display could be something like:

Known compatible with Craft CMS: 3.0, 3.1, 3.2, 3.3, 3.4

This would be a "crowd sourced" voting mechanism. The only issue I foresee could be lack of incentive for people to bother voting.

So you might need to have them listed as working by default, but allow people to vote **NO** if it's not working.

Whenever the author releases a new version of the plugin, this information is reset.

**Comment by brandonkelly** [comment]
I don’t see this really being necessary anymore, now that Craft 4 has weeded out any aboandonware plugins, and we’re now being much more strict about not introducing breaking changes in minor releases. So plugins compatible with 4.0 will be compatible with 4.9.
