### ISSUE TITLE
[FR] Make developers renew their plugins annually

### ISSUE THREAD

**Issue by khalwat** [craftcms/.github#37]
Something that Apple has long done in the App Store is requiring you to log in on at least an annual basis to click on **I Agree** to their Terms Of Service (TOS) once per year.

If you don't, your app becomes de-listed in until you go in and re-publish them.

This does two things:

1 - It keeps you up to date from a legal POV with any TOS changes
2 - It forces the developer to have a minimum bar of interactivity to keep their plugins listed

I'd suggest doing this only for paid plugins, because I think it's reasonable to ask that if developers are being paid for a plugin, they should be available to at least click through the TOS agreement.

**Comment by brandonkelly** [comment]
Same thought as https://github.com/craftcms/.github/issues/36#issuecomment-1338276845. Not really needed anymore since the annual(-ish) release cycle will ensure plugins are only published in the latest Craft version’s Plugin Store if they’ve been updated to support that Craft version.
